export { VERSION } from './version.js';
export {
  MediaLibrary,
  defaultTranslations,
  resolveTranslations,
  translate,
  normalizeValue,
  mapValidationErrors,
  validateFile,
  describeAccept,
  getCsrfHeaders,
  generateUuid,
} from './core/index.js';
export type {
  AfterUploadResult,
  CsrfDocument,
  FileLike,
  InvalidMedia,
  MappedErrors,
  MappedValidationErrors,
  MediaLibraryConfig,
  MediaLibraryState,
  MediaObject,
  MediaObjectErrors,
  MediaValue,
  PartialTranslations,
  ResolvedMediaLibraryConfig,
  TranslationKey,
  Translations,
  UploadInfo,
  UploadRequest,
  UploadResponse,
  UploadTransport,
  UploadTransportResponse,
  ValidationErrorBag,
  ValidationRules,
  ValueItem,
  ValueItemInput,
} from './core/index.js';
